name: Build assets
on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version'
        type: string
      install-composer-dependencies:
        description: 'Whether composer dependencies are needed'
        type: boolean
        default: false
      build-paths:
        description: 'Paths to the assets'
        type: string
        default: 'public/build'
    secrets:
      FLUX_USERNAME:
        description: 'Flux username'
        required: true
      FLUX_LICENSE_KEY:
        description: 'Flux license key'
        required: true
      COMPOSER_AUTH_TOKEN:
        description: 'Composer auth token'
        required: true
      ASSETS_SSH_PRIVATE_KEY:
        description: 'Allow to add SSH private key to install private NPM repo'
        required: false
jobs:
  build-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: 'npm'
      - name: Setup PHP
        if: ${{ inputs.install-composer-dependencies }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: mbstring, dom, fileinfo, mysql
      - name: Add github token to composer config
        if: ${{ inputs.install-composer-dependencies }}
        run: |
          if [ -n "${{ secrets.FLUX_USERNAME }}" ] && [ -n "${{ secrets.FLUX_LICENSE_KEY }}" ]; then
            composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"
          fi
          if [ -n "${{ secrets.COMPOSER_AUTH_TOKEN }}" ]; then
            composer config github-oauth.github.com ${{ secrets.COMPOSER_AUTH_TOKEN }} # github code16 organization secret
          fi
      - name: Get composer cache directory
        if: ${{ inputs.install-composer-dependencies }}
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache composer dependencies
        if: ${{ inputs.install-composer-dependencies }}
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        if: ${{ inputs.install-composer-dependencies }}
        run: composer install --prefer-dist
      - name: Add SSH key for NPM private repository (optional)
        if: ${{ env.ASSETS_SSH_PRIVATE_KEY != '' }}
        uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.ASSETS_SSH_PRIVATE_KEY }}
        env:
          ASSETS_SSH_PRIVATE_KEY: ${{ secrets.ASSETS_SSH_PRIVATE_KEY }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Commit Assets
        run: |
          git add ${{ inputs.build-paths }}
          
          if [ -n "$(git status --porcelain)" ]; then
            git \
              -c user.name="github-actions[bot]" \
              -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "Assets" \
              --author="${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>"
            git push
          else
            echo "Nothing to commit"
          fi

