name: Backup - Poll & Upload latest Organization Migration

on:
  workflow_dispatch:
#  schedule:
    # Runs at 02:30 every day
#    - cron: '30 2 * * *'

env:
  # Define the organization name as an environment variable for easy reuse
  ORG_NAME: "code16"

jobs:
  download-migration:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Migration and Download
        run: |
          echo "Looking for the latest migration..."
          LATEST_MIGRATION=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITBACKUP_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/orgs/$ORG_NAME/migrations | jq '.[0]')
          
          MIGRATION_ID=$(echo "$LATEST_MIGRATION" | jq -r '.id')
          
          if [ "$MIGRATION_ID" == "null" ] || [ -z "$MIGRATION_ID" ]; then
            echo "No recent migrations found."
            exit 1
          fi
          
          echo "Found latest migration ID: $MIGRATION_ID"
          
          while true; do
            STATUS=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITBACKUP_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2026-03-10" \
              https://api.github.com/orgs/$ORG_NAME/migrations/$MIGRATION_ID | jq -r '.state')
          
            if [ "$STATUS" == "exported" ]; then
              echo "Export complete!"
              break
            elif [ "$STATUS" == "failed" ]; then
              echo "Migration failed!"
              exit 1
            fi
          
            echo "Current status is $STATUS. Waiting 30 seconds..."
            sleep 30
          done
          
          echo "Downloading archive..."
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITBACKUP_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            https://api.github.com/orgs/$ORG_NAME/migrations/$MIGRATION_ID/archive \
            -o org-backup-archive.tar.gz

      - name: Upload Backup to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: org-backup-latest
          path: org-backup-archive.tar.gz

