name: Junie

on:
  workflow_call:
    secrets:
      JUNIE_API_KEY:
        description: 'Junie API key'
        required: true

jobs:
  junie:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@junie-agent')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@junie-agent')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@junie-agent')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@junie-agent') || contains(github.event.issue.title, '@junie-agent')))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 1

      - name: Run Junie
        id: junie
        uses: JetBrains/junie-github-action@8c16bc017475d62fe7911701164cb5ceef999f02 # v1
        with:
#          model: claude-opus-4-5-20251101
#          model: gpt-5.2-codex
#          model: gemini-3-pro-preview
          junie_api_key: ${{ secrets.JUNIE_API_KEY }}
