name: Unit tests back
on:
  workflow_call:
    inputs:
      php-version:
        description: 'PHP version'
        type: string
      is-package:
        description: 'Whether the project is a package'
        type: boolean
        default: false
      has-browser-tests:
        description: 'Does the project have Pest Browser tests (e2e)? if so it will install node + playwright'
        type: boolean
        default: false
      test-command:
        description: 'Test command to run'
        type: string
        required: false
      slack-channel-id:
        description: 'Slack channel id'
        type: string
        required: true
      update-shards:
        description: 'Whether to update shards'
        type: boolean
        default: false
    secrets:
      FLUX_USERNAME:
        description: 'Flux username'
        required: false
      FLUX_LICENSE_KEY:
        description: 'Flux license key'
        required: false
      COMPOSER_AUTH_TOKEN:
        description: 'Composer auth token'
        required: false
      SLACK_BOT_TOKEN:
        description: 'Slack bot token'
        required: true
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    env:
      APP_KEY: 'base64:sorUHw3uTOYdZXsJhRA13+2dYiSeG90TMkAHyFDKrVk='
      APP_ENV: testing
      DB_HOST: 127.0.0.1
      DB_CONNECTION: mysql
      DB_DATABASE: our-awesome-tested-app
      DB_USERNAME: root
      DB_PASSWORD: password
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: our-awesome-tested-app
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v6
      - name: Check ray() calls
        uses: code16/detect-laravel-ray-action@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          github-token: ${{ secrets.COMPOSER_AUTH_TOKEN }}
          extensions: mbstring, dom, fileinfo, mysql
      - if: ${{ inputs.has-browser-tests }}
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Add github token to composer config
        run: |
          if [ -n "${{ secrets.FLUX_USERNAME }}" ] && [ -n "${{ secrets.FLUX_LICENSE_KEY }}" ]; then
            composer config http-basic.composer.fluxui.dev "${{ secrets.FLUX_USERNAME }}" "${{ secrets.FLUX_LICENSE_KEY }}"
          fi
          if [ -n "${{ secrets.COMPOSER_AUTH_TOKEN }}" ]; then
            composer config github-oauth.github.com ${{ secrets.COMPOSER_AUTH_TOKEN }} # github code16 organization secret
          fi
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache composer dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: composer install --prefer-dist
      - name: Run Security Audit
        run: composer audit
      - if: ${{ inputs.has-browser-tests }}
        name: Install NPM dependencies
        run: npm ci
      - if: ${{ inputs.has-browser-tests }}
        name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - if: ${{ inputs.has-browser-tests }}
        name: Build assets
        run: npm run build
      - name: Create .env
        if: ${{ !inputs.is-package }}
        run: touch .env
#      - name: Run Migration
#        if: ${{ !inputs.is-package }}
#        run: php artisan migrate -v
#        env:
#          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
      - name: Execute tests
        run: |
          if [ -n "${{ inputs.test-command }}" ]; then
            eval "${{ inputs.test-command }}"
          elif [ -f ./vendor/bin/pest ]; then
            ./vendor/bin/pest --ci ${{ inputs.update-shards == true && '--update-shards' || '' }}
          else
            ./vendor/bin/phpunit --colors=never
          fi
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
      - name: Commit shards.json
        if: ${{ inputs.update-shards }}
        run: |
          git add tests/.pest/shards.json

          if [ -n "$(git status --porcelain)" ]; then
            git \
              -c user.name="github-actions[bot]" \
              -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
            commit -m "Update shards.json" \
              --author="${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>"
            git push
          else
            echo "Nothing to commit"
          fi
      - if: ${{ inputs.has-browser-tests && failure() }}
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: browser-tests-screenshots-logs
          path: |
            tests/Browser/Screenshots
            tests/Browser/Tracing
            tests/Browser/Traces
            storage/logs
      - name: Notify Slack on failure
        uses: code16/.github/.github/actions/slack-notify-failure@main
        if: failure() && (github.base_ref == 'production' || inputs.is-package)
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: ${{ inputs.slack-channel-id }}

